# Generated by Django 4.1.5 on 2023-01-30 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0002_alter_attachment_id_alter_comment_id_alter_log_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='code',
            field=models.CharField(default='AdT6PeuEQbLjFZgqTl0cw5gmImbNEEhF', max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='mensajito',
            field=models.CharField(default='Kami kembali, {self.owner}! ;)', max_length=300),
        ),
    ]
