# Generated by Django 4.1.5 on 2023-01-30 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0003_alter_ticket_code_alter_vacation_mensajito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('Perencanaan', 'Perencanaan'), ('Penganggaran', 'Penganggaran'), ('Pengadaan', 'Pengadaan'), ('Pelaksanaan', 'Pelaksanaan Proyek'), ('Pengawasan', 'Pengawasan Kegiatan'), ('Serah Terima', 'Serah Terima Pekerjaan'), ('Purna Jual', 'Purna Juala'), ('Evaluasi Kegiatan', 'Evaluasi Kegiatan')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='code',
            field=models.CharField(default='HuaAGTK4Br0v', max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='department',
            field=models.CharField(choices=[('Kendari', 'Kejari Kendari'), ('Bombana', 'Kejari Bombana'), ('Kolaka', 'Kejari Kolaka'), ('Kolaka Utara', 'Kejari Kolaka Utara'), ('Muna', 'Kejari Muna'), ('Konsel', 'Kejari Konawe Selatan'), ('Konawe', 'Kejari Konawe'), ('Buton', 'Kejari Buton'), ('Wakatobi', 'Kejari Wakatobi'), ('Baubau', 'Kejari Baubau')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.TextField(help_text='Uraian masalah'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='is_escalated',
            field=models.BooleanField(default=False, help_text='Apakah akan dieskalasi?', verbose_name='eskalasi'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Ongoing', 'On Going'), ('Closed', 'Closed')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='subject',
            field=models.CharField(help_text='Subyek.', max_length=200),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='mensajito',
            field=models.CharField(default='¡Libur! Selamat berlibur', max_length=300),
        ),
    ]
