# Generated by Django 4.1.5 on 2023-01-30 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_account_id_alter_myuser_id_alter_rol_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='is_kejati',
            field=models.BooleanField(default=False),
        ),
    ]
