# Generated by Django 4.1.5 on 2023-01-30 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_rol_is_kejati'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='description',
            field=models.CharField(blank=True, default='User Helpdesk Jaga Desa', max_length=90),
        ),
    ]
